apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: elog-user-secret
spec:
  path: secret/ad/ad-build/core-build-system/deployment-controller
  type: Opaque
  keys:
    - ELOG_USER_PASSWORD
    - ELOG_SW_LOG_ID
